# Generated by Django 3.0.1 on 2020-05-01 11:07

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='User Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Full Name'),
        ),
    ]
